cost-format = "0.00"

csv {
  separator = ";"
  header = false

  # If set to false, it will bill the correct lines while logging the incorrect lines.
  # If set to true, it will reject the whole file if there is an invalid line.
  validate-file = false
}